package com.myspace.listenerproject;

/**
 * This class was automatically generated by the data modeler tool.
 */
 
import org.kie.api.task.TaskEvent;
import org.kie.api.task.TaskLifeCycleEventListener;

public class TaskEventLstr implements java.io.Serializable,TaskLifeCycleEventListener {

    static final long serialVersionUID = 1L;

    public TaskEventLstr() {
    }




}